version: "3.9"
services:
  aliddns2:
    build: .
    ports:
      - "3000:3000"
    environment:
      ALIDDNS_LOG_LEVEL: info
    volumes:
      - ./cmd/aliddns2/config.toml:/usr/local/bin/config.toml

